# -*- coding: utf-8 -*-
"""SCM Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mihxU6mWIDsHRg6AkOu51ZMQST79vNHb
"""

import pandas as pd
from sqlalchemy import create_engine
import numpy as np

!apt-get -qq install -y graphviz && pip install pydot
import pydot

!pip install pymysql sqlalchemy pandas scikit-learn shap

# 1. Connect to MySQL Database
db_user= 'python_angent'
db_password = 'DataSupport2026!'
db_host= 'localhost'
db_name = 'procurement_support_db'

engine = create_engine(f'mysql+pymysql://{db_user}:{db_password}@{db_host}/{db_name}')

# 2. Extract the Granular Feature Data from SQL
print("Extracting historical data from SQL...")
df= pd.read_sql('SELECT * FROM vw_PO_Fulfillment_Features;',engine)

"""UNABLE TO CONNECT WITH LOCAL HOST, TRYING OTHER METHOD"""

#manually uploading dataset

import pandas as pd
import numpy as np

df_scorecard=pd.read_csv('vw_Supplier_Scorecard.csv')

# 2. Calculate Dynamic Safety Stock
# Uses the Z-Score and Demand you established in SQL
df_scorecard['Dynamic_Safety_Stock'] = np.ceil(
    df_scorecard['Service_Level_Z_Score'] * df_scorecard['Lead_Time_Standard_Deviation'] * df_scorecard['Avg_Daily_Demand']
)

# 3. Calculate Economic Order Quantity (EOQ)
# Annual Demand = SQL Daily Demand * 365
annual_demand = df_scorecard['Avg_Daily_Demand'] * 365

# EOQ Formula using the specific costs from SQL
#root(2DS/H)
df_scorecard['Optimal_EOQ'] = np.ceil(
    np.sqrt((2 * annual_demand * df_scorecard['Order_Cost_Per_Order']) / df_scorecard['Holding_Cost_Per_Unit'])
)

# 4. Output the Actionable Support Matrix
print("\n--- Dynamic Inventory Control Targets ---")
display_cols = ['supplier_name', 'material', 'Avg_Daily_Demand', 'Dynamic_Safety_Stock', 'Optimal_EOQ']
print(df_scorecard[display_cols].sort_values(by='material').to_string(index=False))

# 5. Save the optimized targets for Power BI later
df_scorecard.to_csv('Optimized_Inventory_Targets.csv', index=False)
print("\nSuccess! 'Optimized_Inventory_Targets.csv' is ready for Power BI.")

"""#DONE WITH INVENTORY TARGET CALCULATIONS..MOVING AHEAD WITH CRITICALITY INDICATOR"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import shap
import numpy as np

# 1. Load the granular order history
print("Extracting historical order data from CSV...")
df_ml = pd.read_csv('vw_PO_Fulfillment_Features.csv')

# 2. Define the target variable (1 = Delayed, 0 = On-Time/Early)
df_ml['Is_Delayed'] = (df_ml['Days_Delay'] > 0).astype(int)

df_ml.head()

df_ml.describe()

df_ml.info()

# 3. Isolate features known at the exact moment a Purchase Order is created
# Focuses on the supplier identity, the material type, and the scale of the order
X = df_ml[['Supplier_Name', 'Material', 'Qty_Ordered']]
y = df_ml['Is_Delayed']

# Convert categorical text data into numerical binary columns for the ML algorithm
X_encoded = pd.get_dummies(X, drop_first=True)

# Split into 80% training data and 20% testing data
X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, test_size=0.2, random_state=42)

# 4. Train the Random Forest Engine
print("Training the Random Forest classification model...")
rf_model = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')
rf_model.fit(X_train, y_train)

# 5. Generate Predictions and Risk Scores on the test batch
risk_probabilities = rf_model.predict_proba(X_test)[:, 1]

from sklearn.metrics import accuracy_score, mean_absolute_error, mean_squared_error, r2_score

# Predict on the test data
y_pred = rf_model.predict(X_test)

# Calculate metrics
accuracy = accuracy_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print(f"Accuracy Score: {accuracy:.4f}")
print(f"Mean Absolute Error (MAE): {mae:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")
print(f"R-squared (R2): {r2:.4f}")

"""Really bad Model scores as our data is fabricated. Changing criteria for delay flagging. If a supplier's Days_Delayed exceeds their specific Buffer_Days, the production line halts. That is our new 1 (True) for the Machine Learning model."""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score
import shap
import numpy as np

# 1. Load BOTH datasets
print("Loading granular orders and inventory targets...")
df_ml = pd.read_csv('vw_PO_Fulfillment_Features.csv')
df_targets = pd.read_csv('Optimized_Inventory_Targets.csv')

# 2. Merge the Safety Stock targets into the historical orders
# We merge on both Supplier and Material to ensure the exact right targets align
df_inventory = df_targets[['Supplier_Name', 'Material', 'Avg_Daily_Demand', 'Dynamic_Safety_Stock']]
df_ml = df_ml.merge(df_inventory, on=['Supplier_Name', 'Material'], how='left')

# 3. Calculate Buffer Days and define the NEW Stockout Risk Target
# How many days can we survive on safety stock alone?
df_ml['Buffer_Days_Available'] = df_ml['Dynamic_Safety_Stock'] / df_ml['Avg_Daily_Demand']

# NEW TARGET: Is the delay longer than the buffer? (1 = Stockout Risk, 0 = Safe)
df_ml['Is_Stockout_Risk'] = (df_ml['Days_Delay'] > df_ml['Buffer_Days_Available']).astype(int)

# 4. Prepare Data for the Algorithm
# We still use the clues known at the time of ordering
X = df_ml[['Supplier_Name', 'Material', 'Qty_Ordered']]
y = df_ml['Is_Stockout_Risk']

#Train Test Split
X_encoded = pd.get_dummies(X, drop_first=True)
X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, test_size=0.2, random_state=42)

# 5. Train the Random Forest Engine
print("Training the Stockout Risk prediction engine...")
rf_model = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')
rf_model.fit(X_train, y_train)

# 6. Evaluate the New Business Logic
y_pred = rf_model.predict(X_test)
print("\n--- Stockout Risk Model Diagnostics ---")
print(classification_report(y_test, y_pred, target_names=['Safe Buffer', 'Critical Stockout']))

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# Generate the confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Display the confusion matrix
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Safe Buffer', 'Critical Stockout'])
disp.plot(cmap=plt.cm.Blues)
plt.title('Confusion Matrix for Stockout Risk Model')
plt.show()

"""Isnt performing any good to predict critical stockouts, well try by reducing threshold from default 50% to 30%"""

# 6. Evaluate the New Business Logic (with Risk Mitigation Threshold)

# Instead of getting a flat 1 or 0, we extract the exact risk probability (0.0 to 1.0)
y_prob = rf_model.predict_proba(X_test)[:, 1]

# INNOVATION: We lower the threshold. If risk > 30%, we flag it as a Critical Stockout.
custom_threshold = 0.30
y_pred_custom = (y_prob >= custom_threshold).astype(int)

print("\n--- Stockout Risk Model Diagnostics (Adjusted 30% Threshold) ---")
print(classification_report(y_test, y_pred_custom, target_names=['Safe Buffer', 'Critical Stockout']))

# Visualize the new, improved Confusion Matrix
import seaborn as sns
import matplotlib.pyplot as plt
cm_custom = confusion_matrix(y_test, y_pred_custom)
plt.figure(figsize=(6, 4))
sns.heatmap(cm_custom, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Predicted Safe', 'Predicted Stockout'],
            yticklabels=['Actually Safe', 'Actually Stockout'])
plt.title('Prediction Support Matrix (30% Risk Threshold)')
plt.ylabel('Actual Supply Chain Event')
plt.xlabel('Model Prediction')
plt.show()

"""Added More dummy data in sql, retrying again"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import numpy as np

# 1. Load the freshly updated backend data
print("Loading final backend data...")
df_ml = pd.read_csv('vw_PO_Fulfillment_Features.csv')
df_targets = pd.read_csv('Optimized_Inventory_Targets.csv')

# 2. Merge Inventory Targets to calculate operational Stockout Risk
df_inventory = df_targets[['Supplier_Name', 'Material', 'Avg_Daily_Demand', 'Dynamic_Safety_Stock']]
df_ml = df_ml.merge(df_inventory, on=['Supplier_Name', 'Material'], how='left')

# Calculate Buffer Days and define the binary Stockout Target
df_ml['Buffer_Days_Available'] = df_ml['Dynamic_Safety_Stock'] / df_ml['Avg_Daily_Demand']
df_ml['Is_Stockout_Risk'] = (df_ml['Days_Delay'] > df_ml['Buffer_Days_Available']).astype(int)

# 3. Prepare Data for the Algorithm
X = df_ml[['Supplier_Name', 'Material', 'Qty_Ordered']]
y = df_ml['Is_Stockout_Risk']

X_encoded = pd.get_dummies(X, drop_first=True)
X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, test_size=0.2, random_state=42)

# 4. Train the Final Random Forest Engine
print("Training final prediction engine...")
rf_model = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')
rf_model.fit(X_train, y_train)

# 5. Generate Final Risk Scores
# We extract the exact probability (0 to 100%) that an order will cause a stockout
risk_probabilities = rf_model.predict_proba(X_test)[:, 1]

# 6. Export the Results for Power BI
# We copy the original test data so the dashboard has the Supplier Names and Quantities
final_output = df_ml.loc[X_test.index].copy()
final_output['Predicted_Risk_Score'] = np.round(risk_probabilities * 100, 1)

from sklearn.metrics import accuracy_score, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# Calculate accuracy score
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy Score: {accuracy:.4f}")

# Generate the confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Display the confusion matrix
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Safe Buffer', 'Critical Stockout'])
disp.plot(cmap=plt.cm.Blues)
plt.title('Confusion Matrix for Stockout Risk Model')
plt.show()

# 4. Train the Final Random Forest Engine (With Executive Cost-Sensitivity)
print("Training hyper-sensitive prediction engine...")

#**** INNOVATION: We tell the model that missing a Stockout (Class 1)
#*** is 10 TIMES worse than misclassifying a Safe Buffer (Class 0).
executive_weights = {0: 1, 1: 10}

rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    class_weight=executive_weights  # Injecting the custom business logic here
)
rf_model.fit(X_train, y_train)

from sklearn.metrics import accuracy_score, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# Generate predictions with the new weighted model
y_pred_weighted = rf_model.predict(X_test)

# Calculate and print accuracy score
accuracy_weighted = accuracy_score(y_test, y_pred_weighted)
print(f"Accuracy Score (Weighted Model): {accuracy_weighted:.4f}")

# Generate the confusion matrix for the weighted model
cm_weighted = confusion_matrix(y_test, y_pred_weighted)

# Display the confusion matrix
disp_weighted = ConfusionMatrixDisplay(confusion_matrix=cm_weighted, display_labels=['Safe Buffer', 'Critical Stockout'])
disp_weighted.plot(cmap=plt.cm.Blues)
plt.title('Confusion Matrix for Stockout Risk Model (Weighted)')
plt.show()

#OKAYYYY FINALYYY ADDING WEGIHTS WORKEDDD

# 6. Export the Results for Power BI
# We copy the original test data so the dashboard has the Supplier Names and Quantities
final_output = df_ml.loc[X_test.index].copy()
final_output['Predicted_Risk_Score'] = np.round(risk_probabilities * 100, 1)

# Save to the final CSV needed for your visual Control Tower
final_output.to_csv('Predictive_Criticality_Results.csv', index=False)
print("\nSuccess! 'Predictive_Criticality_Results.csv' exported and ready for Power BI.")

# --- COLAB SHAP VISUALIZATION CELL ---
import shap
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

print("[Diagnostics] Generating live SHAP visuals in Colab...")

# 1. Attach SHAP to your already-trained Random Forest model
explainer = shap.TreeExplainer(rf_model)
shap_values = explainer.shap_values(X_test)

# Isolate the 'Stockout' class (Handles differences in SHAP package versions)
# For binary classification, shap_values will be an array of shape (num_samples, num_features, 2)
# We want the SHAP values for the positive class (class 1: Critical Stockout)
shap_values_stockout = shap_values[:, :, 1] # Extracting values for the positive class

# 2. GENERATE THE VISUAL CHART
print("\n--> Displaying SHAP Global Summary Plot...")
plt.figure(figsize=(8, 5))
plt.title("SHAP Global Diagnostics: Drivers of Stockout Risk")

# The summary_plot automatically renders in Colab
shap.summary_plot(shap_values_stockout, X_test, show=False)
plt.show()

# 3. ROOT CAUSE ALERT (Optional: Prints the highest risk order)
test_risk_probs = rf_model.predict_proba(X_test)[:, 1]
highest_risk_idx = np.argmax(test_risk_probs)
riskiest_order = X_test.iloc[[highest_risk_idx]]

shap_vals_single = explainer.shap_values(riskiest_order)
# shap_vals_single will have shape (1, num_features, 2) for a single sample and binary classification
# We need to extract the 1D array for the positive class (index 1)
shap_vals_single_impact = shap_vals_single[0, :, 1]

feature_impacts = pd.DataFrame({
    'Feature': X_test.columns,
    'Impact': shap_vals_single_impact
}).sort_values(by='Impact', key=abs, ascending=False)

print("\n" + "🚨"*15)
print(" CRITICAL ROOT CAUSE ALERT ")
print("🚨"*15)
print(f"Max Stockout Risk: {test_risk_probs[highest_risk_idx]*100:.1f}%\n")
print("Primary drivers pushing this risk up:")
for index, row in feature_impacts.head(3).iterrows():
    if row['Impact'] > 0:
        print(f" ➔ {row['Feature']} (Impact Factor: +{row['Impact']:.3f})")